### Signup
POST http://localhost:8000/api/signup
Content-Type: application/json

{
  "email": "christianjamezz5@gmail.com",
  "password": "password123",
  "username": "user123"
}

### Signup
POST http://localhost:8000/api/signup
Content-Type: application/json

{
  "email": "mary@example.com",
  "password": "password123",
  "username": "user123"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "myuser@example.com",
  "password": "password123"
}


### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "mary@example.com",
  "password": "password123"
}

### Logout
POST http://localhost:8000/api/logout
Content-Type: application/json



### get user geo
GET http://localhost:8000/home/user
Content-Type: application/json

### search geo
POST http://localhost:8000/home/search
Content-Type: application/json

{
  "ip": "66.249.79.32"
}

### add search
POST http://localhost:8000/search/add
Content-Type: application/json

{
  "ip": "66.249.79.32",
  "hostname": "crawl-66-249-79-32.googlebot.com",
  "city": "The Dalles",
  "region": "Oregon",
  "country": "US",
  "loc": "45.5946,-121.1787",
  "org": "AS15169 Google LLC",
  "postal": "97058",
  "timezone": "America/Los_Angeles",
  "readme": "https://ipinfo.io/missingauth"
}


### get all search
GET http://localhost:8000/search/get-all
Content-Type: application/json